### ISSUE TITLE
Migrate to API v9

### ISSUE THREAD

**Issue by vikmind** [sachaos/todoist#196]
Todoist is planning to remove APIv8 on [Nov 30](https://developer.todoist.com/sync/v8#overview), any plans to migrate?

**Comment by sachaos** [comment]
@vikmind Thank you. I didn't know that.
There is no plan to migrate to v9 now.

**Comment by FlohGro-dev** [comment]
so @sachaos is the project on hold now? I can't add tasks anymore like mentioned in #198 i get the same error.
Do you plan updating the CLI?

**Comment by sachaos** [comment]
@FlohGro-dev I've merged #199 and released v0.17.0. Try this please.

**Comment by FlohGro-dev** [comment]
thanks so much @sachaos this works!
interestingly checking the version still shows me 0.15.0 but 0.17.0 is clearly installed

`todoist --version
todoist version 0.15.0`

**Comment by sachaos** [comment]
That's mistake.
Thank you for your report.
